In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split as ttp
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [4]:
df.shape

(918, 12)

In [5]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

## Removing outliers

In [7]:
restingbp_mean = df.RestingBP.mean()
restingbp_std = df.RestingBP.std()
restingbp_upper_limit = restingbp_mean + 3*restingbp_std
restingbp_lower_limit = restingbp_mean - 3*restingbp_std

df1 = df[(df.RestingBP < restingbp_upper_limit) & (df.RestingBP > restingbp_lower_limit)]
df1

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [8]:
cholesterol_mean = df.Cholesterol.mean()
cholesterol_std = df.Cholesterol.std()
cholesterol_upper_limit = cholesterol_mean + 3*cholesterol_std
cholesterol_lower_limit = cholesterol_mean - 3*cholesterol_std

df2 = df1[(df.Cholesterol < cholesterol_upper_limit) & (df.Cholesterol > cholesterol_lower_limit)]
df2

C:\Users\Neville Evan\AppData\Local\Temp\ipykernel_3868\1407282804.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df1[(df.Cholesterol < cholesterol_upper_limit) & (df.Cholesterol > cholesterol_lower_limit)]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [9]:
oldpeak_mean = df.Oldpeak.mean()
oldpeak_std = df.Oldpeak.std()
oldpeak_upper_limit = oldpeak_mean + 3*oldpeak_std
oldpeak_lower_limit = oldpeak_mean - 3*oldpeak_std

df3 = df2[(df.Oldpeak < oldpeak_upper_limit) & (df.Oldpeak > oldpeak_lower_limit)]
df3

C:\Users\Neville Evan\AppData\Local\Temp\ipykernel_3868\483220379.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3 = df2[(df.Oldpeak < oldpeak_upper_limit) & (df.Oldpeak > oldpeak_lower_limit)]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [10]:
df3.shape

(900, 12)

In [11]:
dataset = pd.get_dummies(df3, drop_first = True)
dataset

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,True,False,False,True,True,False,False,True,False
914,68,144,193,1,141,3.4,1,True,False,False,False,True,False,False,True,False
915,57,130,131,0,115,1.2,1,True,False,False,False,True,False,True,True,False
916,57,130,236,0,174,0.0,1,False,True,False,False,False,False,False,True,False
917,38,138,175,0,173,0.0,0,True,False,True,False,True,False,False,False,True

In [12]:
X = dataset.drop('HeartDisease', axis = 1)
y = dataset.HeartDisease

X.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,True,False,True,False,True,False,False,False,True

In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.42859937,  0.46558517,  0.85055001, ..., -0.8221786 ,
        -1.        ,  1.13581527],
       [-0.47580769,  1.6349075 , -0.16584549, ..., -0.8221786 ,
         1.        , -0.88042486],
       [-1.7461966 , -0.11907599,  0.79460163, ..., -0.8221786 ,
        -1.        ,  1.13581527],
       ...,
       [ 0.37111824, -0.11907599, -0.62275723, ...,  1.21628074,
         1.        , -0.88042486],
       [ 0.37111824, -0.11907599,  0.35633935, ..., -0.8221786 ,
         1.        , -0.88042486],
       [-1.64033085,  0.34865294, -0.21246914, ..., -0.8221786 ,
        -1.        ,  1.13581527]])

In [14]:
X_train, X_test, y_train, y_test = ttp(X_scaled,y, test_size = 0.2, random_state = 42)
X_train.shape

(720, 15)

In [15]:
X_test.shape

(180, 15)

In [16]:
svm_model = SVC()
dtc_model = DecisionTreeClassifier()

# SVM classifier stand-alone and bag model

In [17]:
svm_model.fit(X_train,y_train)
svm_model.score(X_test,y_test)

0.8666666666666667

In [18]:
bag_model_svm = BaggingClassifier(
    estimator = svm_model,
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state = 42
)

bag_model_svm.fit(X_train,y_train)
bag_model_svm.oob_score_

0.8666666666666667

# Decision tree classifier stand-alone and bag model

In [19]:
dtc_model.fit(X_train,y_train)
dtc_model.score(X_test,y_test)

0.75

In [20]:
bag_model_dtc = BaggingClassifier(
    estimator = dtc_model,
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state = 42
)

bag_model_dtc.fit(X_train,y_train)
bag_model_dtc.oob_score_

0.8555555555555555

# Bagging has been used to improve the performance of the decision tree algorithm. It is a technique that involves training multiple decision trees on different subsets of the training data and then combining their predictions to produce a final prediction. The idea behind bagging is that by training multiple trees on different subsets of the data, the trees will be less prone to overfitting and will be more robust to noise in the data. This can lead to improved performance on unseen data.

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
bag_model = BaggingClassifier(
    estimator = dtc_model,
    n_estimators = 100,
    max_samples = 0.8,
    oob_score = True,
    random_state = 42
)

scores = cross_val_score(bag_model, X,y, cv = 5)
scores

array([0.85555556, 0.81111111, 0.82777778, 0.8       , 0.72222222])

In [23]:
scores.mean()

0.8033333333333333